import com.kazurayam.webdriverfactory4ks.ApplicationInfoTest
import com.kazurayam.webdriverfactory4ks.AssertTest
import com.kazurayam.webdriverfactory4ks.ChromeDriverFactoryTest
import com.kazurayam.webdriverfactory4ks.ChromeProfileFinderTest
import com.kazurayam.webdriverfactory4ks.ChromeProfileTest
import com.kazurayam.webdriverfactory4ks.OSIdentifierTest

CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(ApplicationInfoTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(AssertTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(ChromeDriverFactoryTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(ChromeProfileFinderTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(ChromeProfileTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(OSIdentifierTest.class)

