import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.thoughtfulwebdriverfactory.chrome.ChromeDriverFactoryTest

runWithJUnitRunner(ChromeDriverFactoryTest.class)
