import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.thoughtfulwebdriverfactory.ApplicationInfoTest
import com.kazurayam.thoughtfulwebdriverfactory.AssertTest
import com.kazurayam.thoughtfulwebdriverfactory.OSIdentifierTest

import com.kazurayam.thoughtfulwebdriverfactory.chrome.ChromeDriverFactoryTest
import com.kazurayam.thoughtfulwebdriverfactory.chrome.ChromeProfileFinderTest
import com.kazurayam.thoughtfulwebdriverfactory.chrome.ChromeProfileTest

runWithJUnitRunner(ApplicationInfoTest.class)
runWithJUnitRunner(AssertTest.class)
runWithJUnitRunner(ChromeDriverFactoryTest.class)
runWithJUnitRunner(ChromeProfileFinderTest.class)
runWithJUnitRunner(ChromeProfileTest.class)
runWithJUnitRunner(OSIdentifierTest.class)

